__version__ = "0.0.1"

from erpnext.stock.doctype.packed_item import packed_item
from frappe.model.document import Document

from erpnext.stock.doctype.serial_and_batch_bundle import serial_and_batch_bundle
from stellance_customizations.overrides.purchase_receipt import custom_validate_value
from stellance_customizations.overrides.serial_and_batch_bundle import custom_get_available_batches, custom_get_qty_based_available_batches,validate_actual_qty
from erpnext.stock.serial_batch_bundle import SerialBatchBundle

from stellance_customizations.overrides.delivery_note import update_packed_item_basic_data,get_product_bundle_items

serial_and_batch_bundle.get_available_batches = custom_get_available_batches
serial_and_batch_bundle.get_qty_based_available_batches = custom_get_qty_based_available_batches

Document.validate_value = custom_validate_value

packed_item.update_packed_item_basic_data = update_packed_item_basic_data
packed_item.get_product_bundle_items = get_product_bundle_items
SerialBatchBundle.validate_actual_qty = validate_actual_qty